_BASE_: "Base-Keypoint-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "https://download.pytorch.org/models/resnet18-5c106cde.pth"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
SOLVER:
  CHECKPOINT_PERIOD: 3535
